"""Utilities for packaging PyBitEngine games into standalone bundles."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Iterable, Sequence

_DEFAULT_PACKAGES: tuple[str, ...] = (
    "sdl2",
    "moderngl",
    "numpy",
    "numba",
    "PIL",
    "PyBitEngine",
)

_DEFAULT_EXCLUDES: tuple[str, ...] = (
    "tkinter",
    "unittest",
    "pydoc",
    "test",
    "email",
    "http",
    "xmlrpc",
    "pytest",
)


def _abs(path: str | os.PathLike) -> str:
    return str(Path(path).expanduser().resolve())


def _validate_paths(paths: Iterable[str], kind: str) -> list[str]:
    resolved: list[str] = []
    for path in paths:
        absolute_path = _abs(path)
        if not os.path.exists(absolute_path):
            raise FileNotFoundError(f"[PE_PAKER] {kind} not found: {path}")
        resolved.append(absolute_path)
    return resolved


def _resolve_base(console: bool, platform: str | None = None) -> str | None:
    target_platform = platform or sys.platform
    if console or target_platform != "win32":
        return None
    return "gui"


def _build_include_files_pairs(
    dirs_abs: Sequence[str],
    files_abs: Sequence[str],
    licenses_dir: str | os.PathLike | None = None,
) -> list[tuple[str, str]]:
    include_files_pairs: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()

    def add_pair(source: str | os.PathLike, destination: str) -> None:
        source_abs = _abs(source)
        if not os.path.exists(source_abs):
            raise FileNotFoundError(f"[PE_PAKER] file or folder not found: {source}")
        key = (source_abs, destination)
        if key in seen:
            return
        seen.add(key)
        include_files_pairs.append((source_abs, destination))

    for directory in dirs_abs:
        add_pair(directory, os.path.basename(directory))
    for file_path in files_abs:
        add_pair(file_path, os.path.basename(file_path))

    if licenses_dir is not None:
        licenses_path = Path(licenses_dir).expanduser().resolve()
        if licenses_path.exists():
            add_pair(licenses_path, "licenses")

    return include_files_pairs


def pack(
    script: str,
    *,
    name: str = "Game",
    version: str = "1.0.0",
    description: str = "",
    author: str = "",
    output_dir: str = "dist",
    include_dirs: Sequence[str] = (),
    include_files: Sequence[str] = (),
    icon: str | None = None,
    console: bool = False,
    extra_packages: Sequence[str] = (),
    extra_excludes: Sequence[str] = (),
    optimize: int = 2,
    clean: bool = True,
    silent: bool = False,
) -> Path:
    """Create a standalone application folder for a PyBitEngine game."""
    try:
        import cx_Freeze
    except ImportError as exc:
        raise RuntimeError(
            "cx_Freeze is not installed. Install it with: pip install cx_Freeze"
        ) from exc

    script_abs = _abs(script)
    if not os.path.isfile(script_abs):
        raise FileNotFoundError(f"[PE_PAKER] script not found: {script}")

    if icon is not None:
        icon = _abs(icon)
        if not os.path.isfile(icon):
            raise FileNotFoundError(f"[PE_PAKER] icon not found: {icon}")

    dirs_abs = _validate_paths(include_dirs, "include_dir")
    files_abs = _validate_paths(include_files, "include_file")

    output_abs = Path(_abs(output_dir))
    build_dir = output_abs / f"_build_{name}"
    final_dir = output_abs / name

    if clean and final_dir.exists():
        shutil.rmtree(final_dir)
    if build_dir.exists():
        shutil.rmtree(build_dir)
    output_abs.mkdir(parents=True, exist_ok=True)

    licenses_dir = Path(__file__).resolve().parent / "licenses"
    include_files_pairs = _build_include_files_pairs(
        dirs_abs,
        files_abs,
        licenses_dir,
    )

    packages = list(dict.fromkeys((*_DEFAULT_PACKAGES, *extra_packages)))
    excludes = list(dict.fromkeys((*_DEFAULT_EXCLUDES, *extra_excludes)))
    base = _resolve_base(console, sys.platform)

    setup_py = build_dir / "setup.py"
    build_dir.mkdir(parents=True, exist_ok=True)

    # Nota: Ho iniettato sys.path.insert per assicurarmi che cx_Freeze
    # riesca a trovare PyBitEngine anche se avviato dalla cartella _build
    setup_code = f"""\
# Generated by PE_PAKER.
import sys
from cx_Freeze import Executable, setup

# Fix critico: aggiunge la cartella di origine al path
sys.path.insert(0, {str(Path.cwd().resolve())!r})

build_exe_options = {{
    "packages":       {packages!r},
    "excludes":       {excludes!r},
    "include_files":  {include_files_pairs!r},
    "optimize":       {optimize},
    "build_exe":      {str(final_dir)!r},
}}

executables = [
    Executable(
        script      = {script_abs!r},
        base        = {base!r},
        target_name = {name!r},
        icon        = {icon!r},
    )
]

setup(
    name        = {name!r},
    version     = {version!r},
    description = {description!r},
    author      = {author!r},
    options     = {{"build_exe": build_exe_options}},
    executables = executables,
)
"""
    setup_py.write_text(setup_code, encoding="utf-8")

    cmd = [sys.executable, str(setup_py), "build_exe"]
    stdout = subprocess.DEVNULL if silent else None
    stderr = subprocess.DEVNULL if silent else None

    try:
        subprocess.run(cmd, cwd=str(build_dir), check=True, stdout=stdout, stderr=stderr)
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(
            f"[PE_PAKER] cx_Freeze failed with exit code {exc.returncode}."
        ) from exc
    finally:
        shutil.rmtree(build_dir, ignore_errors=True)

    if not silent:
        print(f"[PE_PAKER] Package created: {final_dir}")

    return final_dir


__all__ = ["pack"]